export {default as Home} from "../pages/Home/Home.jsx"
export {default as Player} from "../pages/Player/Player.jsx"
export {default as Team} from "../pages/Team/Team.jsx"
export {default as Login} from "../pages/Login/Login.jsx"
export {default as Register} from "../pages/Register/Register.jsx"